//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagGame.Client.Resources.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppSettings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppSettings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TagGame.Client.Resources.Localization.AppSettings", typeof(AppSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppSettings_Settings_Title {
            get {
                return ResourceManager.GetString("AppSettings.Settings.Title", resourceCulture);
            }
        }
        
        internal static string AppSettings_Settings_Theme {
            get {
                return ResourceManager.GetString("AppSettings.Settings.Theme", resourceCulture);
            }
        }
        
        internal static string AppSettings_Settings_Theme_System {
            get {
                return ResourceManager.GetString("AppSettings.Settings.Theme.System", resourceCulture);
            }
        }
        
        internal static string AppSettings_Settings_Theme_Light {
            get {
                return ResourceManager.GetString("AppSettings.Settings.Theme.Light", resourceCulture);
            }
        }
        
        internal static string AppSettings_Settings_Theme_Dark {
            get {
                return ResourceManager.GetString("AppSettings.Settings.Theme.Dark", resourceCulture);
            }
        }
        
        internal static string AppSettings_Settings_Language {
            get {
                return ResourceManager.GetString("AppSettings.Settings.Language", resourceCulture);
            }
        }
        
        internal static string AppSettings_Settings_Language_System {
            get {
                return ResourceManager.GetString("AppSettings.Settings.Language.System", resourceCulture);
            }
        }
        
        internal static string AppSettings_Settings_Language_English {
            get {
                return ResourceManager.GetString("AppSettings.Settings.Language.English", resourceCulture);
            }
        }
        
        internal static string AppSettings_Settings_Language_German {
            get {
                return ResourceManager.GetString("AppSettings.Settings.Language.German", resourceCulture);
            }
        }
        
        internal static string AppSettings_Settings_Notifications {
            get {
                return ResourceManager.GetString("AppSettings.Settings.Notifications", resourceCulture);
            }
        }
        
        internal static string AppSettings_Settings_Notifications_Enabled {
            get {
                return ResourceManager.GetString("AppSettings.Settings.Notifications.Enabled", resourceCulture);
            }
        }
        
        internal static string AppSettings_Settings_Profile {
            get {
                return ResourceManager.GetString("AppSettings.Settings.Profile", resourceCulture);
            }
        }
        
        internal static string AppSettings_Notifications_SettingsChanged {
            get {
                return ResourceManager.GetString("AppSettings.Notifications.SettingsChanged", resourceCulture);
            }
        }
        
        internal static string AppSettings_Settings_Appearance {
            get {
                return ResourceManager.GetString("AppSettings.Settings.Appearance", resourceCulture);
            }
        }
    }
}
