//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagGame.Client.Resources.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ToastMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToastMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TagGame.Client.Resources.Localization.ToastMessages", typeof(ToastMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string failed_create_user {
            get {
                return ResourceManager.GetString("failed-create-user", resourceCulture);
            }
        }
        
        internal static string update_settings {
            get {
                return ResourceManager.GetString("update-settings", resourceCulture);
            }
        }
        
        internal static string player_joined {
            get {
                return ResourceManager.GetString("player-joined", resourceCulture);
            }
        }
        
        internal static string player_left {
            get {
                return ResourceManager.GetString("player-left", resourceCulture);
            }
        }
        
        internal static string roomowner_changed {
            get {
                return ResourceManager.GetString("roomowner-changed", resourceCulture);
            }
        }
        
        internal static string not_created_room {
            get {
                return ResourceManager.GetString("not-created-room", resourceCulture);
            }
        }
        
        internal static string not_created_player {
            get {
                return ResourceManager.GetString("not-created-player", resourceCulture);
            }
        }
        
        internal static string player_not_joined_room {
            get {
                return ResourceManager.GetString("player-not-joined-room", resourceCulture);
            }
        }
        
        internal static string not_found_room {
            get {
                return ResourceManager.GetString("not-found-room", resourceCulture);
            }
        }
        
        internal static string error_sending_request {
            get {
                return ResourceManager.GetString("error-sending-request", resourceCulture);
            }
        }
        
        internal static string player_updated {
            get {
                return ResourceManager.GetString("player-updated", resourceCulture);
            }
        }
    }
}
